
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e2fbc6864d18d3c37b6cde4297ec9fca266d28f1"

[[override]]
  name = "google.golang.org/grpc"
  version = "v1.12.0"

[[override]]
  name = "golang.org/x/sys"
  revision = "43e60d72a8e2bd92ee98319ba9a384a0e9837c08"

[[override]]
  name = "github.com/libopenstorage/openstorage"
  branch = "release-4.0"

[[constraint]]
  name = "github.com/heptio/ark"
  version = "v0.10-beta.1"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~11.3.0-beta"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "~8.0"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
